import { APP, BASE, USER } from '../../core/manager.js';
import { defaultSettings } from '../../data/pluginSetting.js';
import { repairMissingColumnsBeforeCleanup } from './tableStructureRepair.js?v=memon82';
import { ensureSevenTableWorld, normalizeSettingsStructure } from './sevenTableMigration.js?v=memon82';

const RULE_MARK='[角色身份归一规则]'; const NPC_ANCHOR_MARK='[NPC长期发展锚点规则]';
const PLAYER_COLUMNS=['姓名','性别','种族','年龄','修为','灵根/体质','灵力','神识','身体状态','灵石','钱财','技能/术法','擅长','其他状态','外貌特征'];
const compactRules=`\n${RULE_MARK}\n- 表1“角色状态表”仅记录<user>/玩家本人，禁止写入任何NPC。\n- NPC只要已形成可持续识别的具体对象，例如有明确姓名、稳定称呼、亲属/社会关系、身份或其他稳定识别事实，就检查表4“人物主表”是否需要建档或补充；不再用“是否足够重要”作为建档门槛。一次性路人、没有稳定身份且后续无法区分的人可不建档。\n- NPC身份与稳定识别信息进入表4“人物主表”；NPC最新发展状态进入表5“人物发展表”；重大历史节点以及对后续剧情连续性有用、又不适合放入表0～5的已发生事实进入表6“历史事件表”。\n- 记录前先把一句话拆成最小的独立事实，再逐项归位。身份、修炼体系/路径、修为/境界、修炼经历、持续状态、外貌、地点等即使出现在同一句里，也分别判断字段，不把整句话塞进一个格子。\n- 写表4或表5前，先把每一条人物事实绑定到正文中明确的主体。姓名/称呼、年龄、外貌、衣着、能力、地点、关系、目标等只写给其明确主语、指代对象或能够唯一确认的对象；同段出现多个人物时逐人分开核对，不因句子相邻、年龄相近、同为老人/少年或称呼相似而串写。主体无法唯一确认的那条事实暂不写。\n- 表4与表5通过“姓名”关联同一NPC；昵称、外号、道号、职衔、描述性称呼不得因此新建重复角色。\n- NPC首次只有描述性称呼时可暂作姓名；正式名字出现后更新人物主表姓名，人物发展表同步使用正式姓名。真实昵称/外号/道号/稳定职衔写入表4“别名/称呼”。\n- 性别只记录剧情已明确确认的信息；未明确时留空，不根据姓名、外貌或称呼猜测。\n- 表1与表5“修为”只保存角色当前实际境界/阶段本身，例如“炼气中段”；不把修炼体系、种族、修炼年限、瓶颈、感悟、经历或原因拼进修为字段，也不因为战力对应而换算成人族炼气/筑基/金丹等境界。表1中修为、灵根/体质、身份/所属、年龄、外貌、钱财等事实各写入自己的字段。\n- 表4“修炼体系/路径”只保存简洁的修行类别/路线标签，不写解释句。已确认走人族灵根→法力→炼气等常规修仙机制者记“练气士”；已确认妖族开启灵智并实际修行、使用妖力或进入妖族1～10级等体系者记“妖修”；已确认灵族达到可自主修行阶段并按本源/灵体体系修炼者记“灵修”；已确认走一至九品等凡俗武道者记“武夫”。不能只凭种族直接判定路径。\n- 明确主修/兼修路线后，可追加法修、体修、剑修、魂修、旁门、丹师、器师、符师、阵师、御兽等已确认标签；多个标签用“／”连接，如“练气士／剑修”。一次使用某类武器、法术或技艺不足以确认稳定路线/职业；武夫与体修必须区分。\n- 修炼经历、长期停滞、瓶颈、伤势、特殊限制等按事实性质进入表4“重要信息”或表5“当前重要状态”。例如“早年曾引气入体”属于经历，“多年未进”属于长期状态，不属于修炼体系/路径标签，也不属于境界名称。\n- 表1与表4“外貌特征”使用同一外貌判断方法维护；外貌之外的信息按其事实性质归入对应字段或表，不因与外貌出现在同一句叙述中就整体写入外貌。\n- 表4保存NPC已确认的“种族/血脉”和“修炼体系/路径”；不默认人族，不由Memo自行发明种族境界表。\n- 同族不同血脉/族群可有不同成长方式；人物可兼修/转修，但只有剧情明确确认后才更新。\n- 身份证据不足时不要强行合并；确认同一人物后，表4与表5各只保留一条对应记录。\n- 所有属性统一使用“神识”；“神魂”仅在确实指灵魂/魂魄本体时使用。\n- 未知、没有、未提及的内容一律留空，不写占位词，也不得猜测。\n`;
const npcAnchorRules=`\n${NPC_ANCHOR_MARK}\n- Memo只保存NPC长期发展锚点，不自行模拟离线成长，不为NPC成长额外编造事实。\n- 表4“人物主表”负责识别NPC是谁：姓名、性别、别名/称呼、身份/所属、外貌特征、性格、与玩家关系、重要信息，以及已确认的种族/血脉、修炼体系/路径。达到“可持续识别”即可建档，不要求先成为重大人物。\n- 表5“人物发展表”负责NPC最后有效发展锚点：姓名、原生修为/境界、主要能力、当前地点、年龄、最后确认时间、当前重要状态、主要目标/重要事项。\n- “修炼体系/路径”“修为”“修炼经历/状态”是三类不同事实：表4体系/路径使用短标签记录人物属于哪类修行者、走什么稳定路线；表5修为只保存当前境界/阶段；过去经历写表4重要信息，当前瓶颈、停滞、伤势、限制等写表5当前重要状态。同一句出现多类事实时拆开维护。\n- 基础修行类别按已确认机制归一：人族常规灵根/法力/炼气体系→“练气士”；妖族实际修行→“妖修”；灵族达到自主修行并实际修炼→“灵修”；一至九品等凡俗武道→“武夫”。种族本身只是证据之一，不能单独决定修炼路径；普通野兽不等于妖修，未达到自主修行阶段的灵物不等于灵修。\n- 已明确的法修、体修、剑修、魂修、旁门、丹师、器师、符师、阵师、御兽等主修/兼修路线可追加到基础类别，多个标签用“／”连接；不得因单次使用武器、法术或技艺就擅自加标签。武夫≠体修。\n- “修为”字段只记录该NPC自己的境界名称/阶段；“实力约等于某境界”不是修为，不得据此改写；“二十年未进”等持续时间也不是修为字段的一部分。\n- “年龄”和“最后确认时间”是两个独立字段：年龄记录人物当时已确认的年龄；最后确认时间记录这条发展锚点最后被剧情明确确认的世界日期，精确到日即可，不要求时、分。不得互相代替；任一未知则留空。\n- 每次准备更新表4/5时，先核对“这条事实是谁的”：拟写入姓名必须就是正文中该事实的明确主体；表5目标row第一列姓名必须与该人物一致。若正文同时出现多个NPC，分别核对后再写。\n- NPC再次进入当前剧情时，联合读取表4该NPC主记录 + 表5最新发展锚点 + 表6中与其相关的既成事件，作为正文模型离线发展推演起点。\n- 正文确认新的原生修为、地点、年龄、确认日期、状态、目标等后，只更新实际发生变化或新确认的对应字段，形成新锚点；种族/血脉、修炼体系/路径、身份/所属、关系或长期重要信息变化时同步update表4。新锚点取代旧状态，禁止从旧时期重复结算。\n- 表6既记录影响未来推演的重大节点，也记录0～5没有合适字段但后续剧情需要知道的已发生事实，例如异常发现、关键交互、决定、线索、关系转折或连续事件。连续事件优先压缩维护同一条记录，不按每轮机械新增；纯氛围和无后续意义的琐碎动作不单独记录。\n- 表5最新状态与表6既成事件冲突时，以时间更晚且已明确发生的事实为准。\n`;
function replaceMarkedBlock(text,mark,block){const value=String(text||'');if(!value.includes(mark))return value+block;const escaped=mark.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return value.replace(new RegExp(`\\n${escaped}[\\s\\S]*?(?=\\n#|\\n\\[[^\\n]+\\]|$)`),block.trimEnd());}
function appendRules(text){return replaceMarkedBlock(replaceMarkedBlock(text,RULE_MARK,compactRules),NPC_ANCHOR_MARK,npcAnchorRules);}
function preserveSingleApiProtocol(oldText,nextText){const value=String(oldText||'');const start=value.indexOf('[一次API固定收尾协议]');if(start<0)return nextText;const endMark='[/一次API固定收尾协议]';const end=value.indexOf(endMark,start);if(end<0)return nextText;const block=value.slice(start,end+endMark.length);return`${String(nextText||'').trim()}\n\n${block}`.trim();}
function normalizeAgeAnchorPrompt(text){return String(text||'').replace(/年龄或最后确认时间/g,'年龄、最后确认时间').replace(/年龄\/最后确认时间/g,'年龄、最后确认时间').replace(/年龄\/时间/g,'年龄、确认时间');}
function upgradeKnownOldPrompts(settings){const message=String(settings?.message_template||'');if(message.includes('## 表格：0当前状态 / 1角色状态 / 2背包 / 3当前任务与约定 / 4人物 / 5历史事件')||message.includes('六张表维护当前事实状态'))settings.message_template=preserveSingleApiProtocol(message,defaultSettings.message_template);const refreshSystem=String(settings?.refresh_system_message_template||'');if(refreshSystem.includes('人物表保存NPC最后有效发展锚点')||refreshSystem.includes('现有六张表'))settings.refresh_system_message_template=defaultSettings.refresh_system_message_template;const refreshUser=String(settings?.refresh_user_message_template||'');if(refreshUser.includes('4人物→5历史事件')||refreshUser.includes('六张表'))settings.refresh_user_message_template=defaultSettings.refresh_user_message_template;}
function patchPrompts(settings){if(!settings||typeof settings!=='object')return;normalizeSettingsStructure(settings);if(settings!==defaultSettings)upgradeKnownOldPrompts(settings);if('message_template'in settings)settings.message_template=appendRules(normalizeAgeAnchorPrompt(settings.message_template));if('refresh_system_message_template'in settings)settings.refresh_system_message_template=appendRules(normalizeAgeAnchorPrompt(settings.refresh_system_message_template));if('refresh_user_message_template'in settings)settings.refresh_user_message_template=appendRules(normalizeAgeAnchorPrompt(settings.refresh_user_message_template));}
function normalized(values){return(values||[]).map(value=>String(value||'').trim());}
function migrateLegacyPlayerSheet(){let sheet;let backup;try{const piece=USER.getChatPiece?.()?.piece;if(!piece)return false;sheet=BASE.getChatSheets().find(item=>item?.name==='角色状态表');if(!sheet)return false;const header=normalized(sheet.getHeader?.()||[]);if(header.length===PLAYER_COLUMNS.length&&PLAYER_COLUMNS.every((v,i)=>header[i]===v))return false;const old=PLAYER_COLUMNS.filter(col=>col!=='性别');if(header.length!==old.length||!old.every((v,i)=>header[i]===v))return false;const valueSheet=sheet.getContent?.(true);if(!Array.isArray(valueSheet)||!valueSheet.length)return false;backup=sheet.filterSavingData?.();const migrated=valueSheet.map((row,rowIndex)=>{const next=Array.isArray(row)?row.slice():[];next.splice(2,0,rowIndex===0?'性别':'');return next;});sheet.rebuildHashSheetByValueSheet(migrated);sheet.markPositionCacheDirty?.();if(sheet.save(piece,true)===false)throw new Error('角色状态表迁移快照保存失败');USER.saveChat();return true;}catch(error){if(sheet&&backup){try{sheet.loadJson(backup);}catch(rollbackError){console.error('[Memo] 角色状态表旧结构迁移回滚失败',rollbackError);}}console.warn('[Memo] 角色状态表旧结构迁移失败，保留原数据',error);return false;}}
function patchCurrentSettingsAndData(){patchPrompts(USER?.tableBaseSetting);migrateLegacyPlayerSheet();ensureSevenTableWorld();}
function safePatchCurrentSettingsAndData(){try{patchCurrentSettingsAndData();repairMissingColumnsBeforeCleanup({notify:false});}catch(error){console.warn('[Memo] 七表结构迁移跳过：不阻断正常聊天/记录',error);}}
function repairBeforePrompt(){try{patchCurrentSettingsAndData();repairMissingColumnsBeforeCleanup({notify:false});}catch(error){console.warn('[Memo] 请求前七表校验失败，已降级继续生成，不阻断一次API/独立记录',error);}}

try{patchPrompts(defaultSettings);}catch(error){console.warn('[Memo] 默认提示规则补丁失败，继续加载',error);}
queueMicrotask(safePatchCurrentSettingsAndData);setTimeout(safePatchCurrentSettingsAndData,250);setTimeout(safePatchCurrentSettingsAndData,1000);setTimeout(safePatchCurrentSettingsAndData,2000);
const promptEvent=APP.event_types.CHAT_COMPLETION_PROMPT_READY;APP.eventSource.on(promptEvent,repairBeforePrompt);if(typeof APP.eventSource.makeFirst==='function')APP.eventSource.makeFirst(promptEvent,repairBeforePrompt);
console.log('[Memo] 七表职责/NPC发展锚点已加载；修炼体系/路径使用练气士、妖修、灵修、武夫及明确流派的规范化标签');
