import { BASE, USER } from '../../core/manager.js';
import { Cell } from '../../core/table/cell.js';
import JSON5 from '../../utils/json5.min.mjs';

const ACTION_NAMES=new Set(['insertRow','updateRow','deleteRow']);
function norm(value){return String(value??'').trim();}
function copyValue(value){if(value===undefined)return undefined;try{return structuredClone(value);}catch(_){return JSON.parse(JSON.stringify(value));}}
function copyHash(value){if(!value||typeof value!=='object')return null;try{return BASE.copyHashSheets(value);}catch(_){return copyValue(value);}}
function visiblePromptSheets(){return(BASE.getChatSheets?.()??[]).filter(sheet=>sheet?.enable).filter(sheet=>sheet?.sendToContext!==false);}
function tableNameForIndex(tableIndex){const index=Number(tableIndex);if(!Number.isInteger(index)||index<0)return null;return norm(visiblePromptSheets()[index]?.name)||null;}
function sheetForIndex(tableIndex){const index=Number(tableIndex);if(!Number.isInteger(index)||index<0)return null;return visiblePromptSheets()[index]??null;}
function quoteNumericObjectKeys(text){const source=String(text??'');let output='';let quote=null;let escaped=false;for(let i=0;i<source.length;i++){const ch=source[i];if(quote){output+=ch;if(escaped)escaped=false;else if(ch==='\\')escaped=true;else if(ch===quote)quote=null;continue;}if(ch==='"'||ch==="'"||ch==='`'){quote=ch;output+=ch;continue;}output+=ch;if(ch!=='{'&&ch!==',')continue;let cursor=i+1;while(cursor<source.length&&/\s/.test(source[cursor]))cursor++;const start=cursor;while(cursor<source.length&&/\d/.test(source[cursor]))cursor++;if(cursor===start)continue;let colon=cursor;while(colon<source.length&&/\s/.test(source[colon]))colon++;if(source[colon]!==':')continue;output+=source.slice(i+1,start)+`"${source.slice(start,cursor)}"`+source.slice(cursor,colon);i=colon-1;}return output;}
function extractCalls(text){const source=String(text??'');const calls=[];const spans=[];let i=0;while(i<source.length){const match=/(insertRow|updateRow|deleteRow)\s*\(/g;match.lastIndex=i;const found=match.exec(source);if(!found)break;const name=found[1];let cursor=match.lastIndex;let depth=1;let quote=null;let escaped=false;for(;cursor<source.length;cursor++){const ch=source[cursor];if(quote){if(escaped)escaped=false;else if(ch==='\\')escaped=true;else if(ch===quote)quote=null;continue;}if(ch==='"'||ch==="'"||ch==='`'){quote=ch;continue;}if(ch==='(')depth++;else if(ch===')'){depth--;if(depth===0)break;}}if(depth!==0)return{ok:false,error:`${name} 缺少右括号`,calls:[],residue:''};const argsText=source.slice(match.lastIndex,cursor);let args;try{args=JSON5.parse(`[${quoteNumericObjectKeys(argsText)}]`);}catch(error){return{ok:false,error:`${name} 参数无法解析：${error?.message||error}`,calls:[],residue:''};}calls.push({name,args});spans.push([found.index,cursor+1]);i=cursor+1;}let residue=source;for(let index=spans.length-1;index>=0;index--){const[start,end]=spans[index];residue=`${residue.slice(0,start)}${residue.slice(end)}`;}return{ok:true,calls,residue};}
function normalizeBlocks(raw){const list=Array.isArray(raw)?raw:[raw];return list.map(value=>String(value??'').replace(/^\s*<tableEdit>\s*/i,'').replace(/\s*<\/tableEdit>\s*$/i,'').replace(/^\s*<!--\s*/,'').replace(/\s*-->\s*$/,'').trim()).filter(Boolean);}
function strictIndex(value){if(typeof value==='number')return Number.isSafeInteger(value)&&value>=0?value:null;if(typeof value==='string'&&/^(?:0|[1-9]\d*)$/.test(value)){const parsed=Number(value);return Number.isSafeInteger(parsed)?parsed:null;}return null;}
function validateData(data,columnCount,label){if(!data||typeof data!=='object'||Array.isArray(data))return{ok:false,error:`${label} data必须是对象`};const keys=Object.keys(data);if(!keys.length)return{ok:false,error:`${label} data不能为空对象`};for(const key of keys){const col=strictIndex(key);if(col===null||col>=columnCount)return{ok:false,error:`${label} 列${key}无效或越界`};const value=data[key];if(typeof value!=='string'&&(typeof value!=='number'||!Number.isFinite(value)))return{ok:false,error:`${label} 列${key}的值必须是字符串或有限数字`};}return{ok:true,error:''};}
function validateAction(call){if(!ACTION_NAMES.has(call?.name))return{ok:false,error:'未知操作'};const args=call.args||[];const expected=call.name==='updateRow'?3:2;if(args.length!==expected)return{ok:false,error:`${call.name}参数数量必须为${expected}，实际为${args.length}`};const[tableIndex,arg1,arg2]=args;const index=strictIndex(tableIndex);if(index===null)return{ok:false,error:`${call.name} tableIndex必须是非负安全整数`};const sheet=sheetForIndex(index);if(!sheet)return{ok:false,error:`#${index} ${tableNameForIndex(index)||'未知/不可见表'} 不存在`};const columnCount=Math.max(0,Number(sheet.getHeader?.().length)||0);const rowCount=Math.max(0,Number(sheet.getRowCount?.())-1||0);if(call.name==='insertRow'){const data=arg1;const checked=validateData(data,columnCount,`insertRow(${index})`);if(!checked.ok)return checked;return{ok:true,action:{type:'insert',tableIndex:index,sheet,data}};}const rowIndex=strictIndex(arg1);if(rowIndex===null||rowIndex>=rowCount)return{ok:false,error:`${call.name}(${index}) rowIndex=${arg1}无效或越界；当前数据行数=${rowCount}`};if(call.name==='deleteRow')return{ok:true,action:{type:'delete',tableIndex:index,sheet,rowIndex}};const data=arg2;const checked=validateData(data,columnCount,`updateRow(${index},${rowIndex})`);if(!checked.ok)return checked;return{ok:true,action:{type:'update',tableIndex:index,sheet,rowIndex,data}};}
function validateBatch(actions){const deleted=new Set();const updated=new Set();const updatedColumns=new Map();for(const action of actions){if(action.type!=='delete'&&action.type!=='update')continue;const key=`${action.tableIndex}:${action.rowIndex}`;if(action.type==='delete'){if(deleted.has(key))return{ok:false,error:`同一批操作重复删除 #${action.tableIndex} row=${action.rowIndex}`};deleted.add(key);continue;}updated.add(key);let columns=updatedColumns.get(key);if(!columns){columns=new Set();updatedColumns.set(key,columns);}for(const column of Object.keys(action.data)){if(columns.has(column))return{ok:false,error:`同一批操作重复更新 #${action.tableIndex} row=${action.rowIndex} col=${column}`};columns.add(column);}}for(const key of deleted){if(updated.has(key)){const[tableIndex,rowIndex]=key.split(':');return{ok:false,error:`同一批操作不能同时更新并删除 #${tableIndex} row=${rowIndex}`};}}return{ok:true,error:''};}
function ordered(actions){const priority={update:0,insert:1,delete:2};return[...actions].sort((a,b)=>{if(a.type==='delete'&&b.type==='delete'&&a.tableIndex===b.tableIndex)return b.rowIndex-a.rowIndex;return priority[a.type]-priority[b.type];});}
function applyAction(action){const sheet=action.sheet;if(action.type==='update'){for(const[key,value]of Object.entries(action.data)){const cell=sheet.findCellByPosition(action.rowIndex+1,Number(key)+1);if(!cell)throw new Error(`updateRow #${action.tableIndex} 找不到单元格 row=${action.rowIndex} col=${key}`);cell.newAction(Cell.CellAction.editCell,{value},false);}return;}if(action.type==='insert'){const anchor=sheet.findCellByPosition(sheet.getRowCount()-1,0);if(!anchor)throw new Error(`insertRow #${action.tableIndex} 找不到插入锚点`);anchor.newAction(Cell.CellAction.insertDownRow,{},false);const row=sheet.getCellsByRowIndex(sheet.getRowCount()-1);if(!row)throw new Error(`insertRow #${action.tableIndex} 插入后无法读取新行`);for(const[key,value]of Object.entries(action.data)){const cell=row[Number(key)+1];if(!cell)throw new Error(`insertRow #${action.tableIndex} 找不到列${key}`);cell.data.value=value;}return;}const cell=sheet.findCellByPosition(action.rowIndex+1,0);if(!cell)throw new Error(`deleteRow #${action.tableIndex} 找不到row=${action.rowIndex}`);cell.newAction(Cell.CellAction.deleteSelfRow,{},false);}
function ensureExtra(target){if(!target.extra||typeof target.extra!=='object')target.extra={};return target.extra;}
function storeSwipeSnapshot(piece){if(!piece?.memo_n_hash_sheets)return;const snapshot=copyHash(piece.memo_n_hash_sheets);ensureExtra(piece).memo_n_swipe_hash_sheets=snapshot;const id=Number(piece?.swipe_id);if(!Number.isInteger(id)||id<0)return;if(!Array.isArray(piece.swipe_info))piece.swipe_info=[];if(!piece.swipe_info[id]||typeof piece.swipe_info[id]!=='object')piece.swipe_info[id]={};if(!piece.swipe_info[id].extra||typeof piece.swipe_info[id].extra!=='object')piece.swipe_info[id].extra={};piece.swipe_info[id].extra.memo_n_swipe_hash_sheets=copyHash(snapshot);delete piece.swipe_info[id].memo_n_swipe_hash_sheets;}
export function saveMemoSnapshot(piece,sheets=BASE.getChatSheets?.()??[]){if(!piece)throw new Error('无法获取当前聊天片段，未保存');for(const sheet of sheets){if(!sheet||typeof sheet.save!=='function')continue;const saved=sheet.save(piece,true);if(saved===false)throw new Error(`保存表格 ${sheet.name||sheet.uid||'未知表'} 失败`);}storeSwipeSnapshot(piece);return true;}
function snapshotSheets(sheets){const snapshots=new Map();for(const sheet of sheets){try{const data=sheet?.filterSavingData?.();if(!data||typeof data!=='object')throw new Error('表格不支持完整序列化');snapshots.set(sheet,copyValue(data));}catch(error){console.error('[Memo][safe-executor] 无法建立完整表格回滚快照',sheet?.name,error);throw error;}}return snapshots;}
function rollbackSnapshots(snapshots){const failures=[];for(const[sheet,data]of snapshots.entries()){try{sheet.loadJson(copyValue(data));}catch(error){failures.push(`${sheet?.name||'未知表'}: ${error?.message||error}`);console.error('[Memo][safe-executor] 完整回滚表格失败',sheet?.name,error);}}return failures;}
export function restoreMemoSnapshot(snapshot){if(!snapshot||typeof snapshot!=='object')return{ok:false,error:'表格快照为空或格式无效'};let liveSnapshots;try{liveSnapshots=snapshotSheets(new Set(BASE.getChatSheets?.()??[]));const restored=BASE.hashSheetsToSheets(copyHash(snapshot));if(!Array.isArray(restored)||restored.length===0)throw new Error('快照恢复未返回任何表格');return{ok:true,error:''};}catch(error){const rollbackFailures=liveSnapshots?rollbackSnapshots(liveSnapshots):[];const suffix=rollbackFailures.length?`；回滚异常：${rollbackFailures.join('；')}`:'';return{ok:false,error:`${error?.message||error}${suffix}`};}}
function snapshotPieceState(piece){const id=Number(piece?.swipe_id);const info=Array.isArray(piece?.swipe_info)&&Number.isInteger(id)&&id>=0?piece.swipe_info[id]:undefined;return{hadHash:Object.prototype.hasOwnProperty.call(piece??{},'memo_n_hash_sheets'),hash:copyHash(piece?.memo_n_hash_sheets),extra:copyValue(piece?.extra),swipeId:id,hadSwipeInfo:Array.isArray(piece?.swipe_info)&&Number.isInteger(id)&&id>=0&&id<piece.swipe_info.length,swipeInfo:copyValue(info),contextSheets:copyValue(BASE.sheetsData?.context)};}
function restorePieceState(piece,state){if(!piece||!state)return;if(state.hadHash)piece.memo_n_hash_sheets=copyHash(state.hash);else delete piece.memo_n_hash_sheets;piece.extra=copyValue(state.extra)??{};if(BASE.sheetsData)BASE.sheetsData.context=copyValue(state.contextSheets)??[];const id=state.swipeId;if(Number.isInteger(id)&&id>=0){if(!Array.isArray(piece.swipe_info))piece.swipe_info=[];if(state.hadSwipeInfo)piece.swipe_info[id]=copyValue(state.swipeInfo);else if(id<piece.swipe_info.length)piece.swipe_info[id]=undefined;}}

export function parseMemoTableEdit(raw){const blocks=normalizeBlocks(raw);if(!blocks.length)return{ok:false,noChange:false,actions:[],error:'没有tableEdit内容'};const joined=blocks.join('\n');const noChange=/\bNO_CHANGE\b/i.test(joined);const parsed=extractCalls(joined);if(!parsed.ok)return{ok:false,noChange:false,actions:[],error:parsed.error};if(noChange&&parsed.calls.length)return{ok:false,noChange:false,actions:[],error:'NO_CHANGE不能与实际表格操作同时出现'};if(noChange){const residue=joined.replace(/\bNO_CHANGE\b/ig,'').replace(/[\s;,]+/g,'');if(residue)return{ok:false,noChange:false,actions:[],error:`NO_CHANGE之外存在无法识别的内容：${residue.slice(0,80)}`};return{ok:true,noChange:true,actions:[],error:''};}const residue=String(parsed.residue??'').replace(/[\s;,]+/g,'');if(residue)return{ok:false,noChange:false,actions:[],error:`存在无法识别或不允许的tableEdit内容：${residue.slice(0,80)}`};if(!parsed.calls.length)return{ok:false,noChange:false,actions:[],error:'没有可执行的insertRow/updateRow/deleteRow，也不是NO_CHANGE'};const actions=[];for(const call of parsed.calls){const checked=validateAction(call);if(!checked.ok)return{ok:false,noChange:false,actions:[],error:checked.error};actions.push(checked.action);}const batch=validateBatch(actions);if(!batch.ok)return{ok:false,noChange:false,actions:[],error:batch.error};return{ok:true,noChange:false,actions:ordered(actions),error:''};}
export function executeMemoTableEdit(raw,piece=null){const parsed=parseMemoTableEdit(raw);if(!parsed.ok)return{ok:false,changed:false,noChange:false,count:0,error:parsed.error};const targetPiece=piece||USER.getChatPiece?.()?.piece;if(!targetPiece)return{ok:false,changed:false,noChange:false,count:0,error:'无法获取当前聊天片段，未保存'};const pieceState=snapshotPieceState(targetPiece);if(parsed.noChange){try{saveMemoSnapshot(targetPiece);return{ok:true,changed:false,noChange:true,count:0,error:''};}catch(error){restorePieceState(targetPiece,pieceState);return{ok:false,changed:false,noChange:false,count:0,error:`保存NO_CHANGE快照失败：${error?.message||error}`};}}
    const touched=new Set(parsed.actions.map(action=>action.sheet));let snapshots;try{snapshots=snapshotSheets(touched);}catch(error){return{ok:false,changed:false,noChange:false,count:0,error:`建立事务快照失败：${error?.message||error}`};}try{for(const action of parsed.actions)applyAction(action);saveMemoSnapshot(targetPiece);return{ok:true,changed:true,noChange:false,count:parsed.actions.length,error:''};}catch(error){const rollbackFailures=rollbackSnapshots(snapshots);restorePieceState(targetPiece,pieceState);const suffix=rollbackFailures.length?`；回滚异常：${rollbackFailures.join('；')}`:'';return{ok:false,changed:false,noChange:false,count:0,error:`执行失败，已回滚且未保存：${error?.message||error}${suffix}`};}}
